title: Trail Sangha
tagline: "Hiking-oriented Zen group in New York City."
email: tailshanga@gmail.com
description: > 
  We are a hiking-oriented Zen group in New York City.
  
  Our pracice schedule consists of walks and hikes in and around the NYC area that are accessible by public transit, including overnight and multi-day backpacking trips.  
  
  We pracice year round, in all kinds of weather.

  All are welcome, including those new to hiking, packpacking and Zen practice.  
author:
  name: Trail Sangha
url: https://www.trailsangha.com
baseurl: /

# Ignore by Jekyll (Compare to '.gitignore')
#
# Excluded files don't spawn regeneration, even if Jekyll ignores files
# beginning with a period or underscore.
exclude:
  - .bundle
  - .git
  - .github
  - _drafts
  - _etc
  - vendor
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - assets/_README-assets.md
  - assets/css/_README-img.md
  - assets/libs/_tar
  - assets/libs/_README-libs.md

# Embed HTML classes/styling in markdown.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: false

# Some libs contain Sass code.
sass:
  load_paths:
    - _sass
    - assets/libs
  style: expanded
  #style: compact

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
    
relative_links:
  enabled:     true
  collections: false

defaults:
  -
    scope:
      path: "" 
    values:
      layout: default
      components: []
      hotbuttons: false

