url: https://www.trailsangha.com

timezone: "America/New_York"
encoding: "utf-8"

# Files and dirs beginning with dot or underscore are not processed by Jekyll
# itself, but still induce site regeneration. Excluding them here prevents 
# regeneration, too.
exclude:
  - .bundle
  - .git
  - .github
  - _drafts
  - _etc
  - assets/_README-assets.md
  - assets/css/_README-img.md
  - assets/css/img/_sources
  - assets/libs/_tar
  - assets/libs/fullcalendar/css/main.css
  - assets/libs/fullcalendar/js/main.js
  - assets/libs/leaflet.fullscreen/js/leaflet.fullscreen.js
  - assets/libs/_README-libs.md
  - vendor
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

defaults:
  -
    scope:
      path: "" # Empty string = All files in project.
    values:
      layout: default
      components: []
      hotbuttons: false
      assets:
        js: []

strict_front_matter: true
liquid:
  error_mode: strict
  strict_filters: true 
  strict_variables: false # 'true' breaks jekyll-sitemap plugin.

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap  # Breaks liquid: strict_filters: true
  - jekyll-relative-links

    # relative_links:
    #   enabled: true
    #   collections: false

sass:
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/libs
  style: expanded

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: false

